colorscheme mine
set nu rnu
syntax on

filetype plugin indent on 
set shiftwidth=4
set textwidth=80
set splitbelow splitright
set autoindent smartindent

set cursorlineopt=number
set cursorline
set incsearch
set ignorecase smartcase

set wildmenu
set wildoptions=fuzzy
set hidden
set wildignore=*.git/*

"StatusLine
set laststatus=2
set statusline=%<%t\ %h%w%m%r%=%-14.(%l,%c%V%)\ %P

source ~/.vim/custom/mapping.vim
runtime ftplugin/man.vim
set keywordprg=:Man

set noesckeys
set shm+=IC
set history=200
set gp=git\ grep\ -n
"set autochdir
packadd! comment
